// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"=================0","status":true,"description":"=====================================","parameters":{}},
{"name":"SkipTitle","status":true,"description":"","parameters":{}},
{"name":"QJ-Core","status":true,"description":"[Core Of QJPlugin][V1.0]","parameters":{}},
{"name":"=================1","status":true,"description":"=====================================","parameters":{}},
{"name":"QJ-TextCodeEx","status":true,"description":"[Expand The Text Code][V1.0]","parameters":{"voice":"[\"{\\\"id\\\":\\\"author\\\",\\\"list\\\":\\\"[\\\\\\\"N-1\\\\\\\",\\\\\\\"N-2\\\\\\\",\\\\\\\"N-3\\\\\\\",\\\\\\\"N-4\\\\\\\",\\\\\\\"N-5\\\\\\\"]\\\",\\\"volume\\\":\\\"100\\\"}\"]","replaceText":"[\"User\"]"}},
{"name":"=================2","status":true,"description":"=====================================","parameters":{}},
{"name":"=================3","status":true,"description":"=====================================","parameters":{}},
{"name":"=================4","status":true,"description":"=====================================","parameters":{}},
{"name":"=================5","status":true,"description":"=====================================","parameters":{}},
{"name":"=================6","status":true,"description":"=====================================","parameters":{}},
{"name":"=================7","status":true,"description":"=====================================","parameters":{}},
{"name":"=================8","status":true,"description":"=====================================","parameters":{}},
{"name":"=================9","status":true,"description":"=====================================","parameters":{}}
];
